### PR TITLE
update Constants.XML_BINDINGS_NAMESPACE

### PR DESCRIPTION
**Pull request by gschwind**

### CODE REVIEW

**Comment by gschwind** [comment]
Should fix the issue #86

**Comment by EHJ-52n** [comment]
@gschwind Thanks for pointing me at this issue. I should add a test for this!

Are you willing to contribute this?

If yes, you need to follow these instructions: http://52north.org/about/licensing/cla-guidelines

**Comment by gschwind** [comment]
Hello, I sent a question about CLA to cla@52north.org to resolve this issue :)

Best regards

**Comment by EHJ-52n** [comment]
This PR is closed and not merged, because 73d8e9f introduces a more dynamic solution.

@gschwind Thank you very much for your time and contribution!

**Pull request closed without merging**
